"""Generate the original P.A.T.C.H. UI-less PDF fixtures.

The output is deterministic except for PDF metadata timestamps generated by
ReportLab. All asset facts are fictional and must remain marked TEST ONLY.
"""

from __future__ import annotations

import io
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Flowable,
    Image as RLImage,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "pdfs" / "fixtures"

NAVY = colors.HexColor("#102A43")
BLUE = colors.HexColor("#1677A6")
CYAN = colors.HexColor("#25A7C7")
SLATE = colors.HexColor("#526777")
PALE = colors.HexColor("#EAF4F8")
AMBER = colors.HexColor("#D98B19")
RED = colors.HexColor("#B42318")
GREEN = colors.HexColor("#157A5A")
LIGHT = colors.HexColor("#F5F8FA")
WHITE = colors.white

PAGE_W, PAGE_H = A4


styles = getSampleStyleSheet()
styles.add(
    ParagraphStyle(
        name="DocTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=27,
        textColor=NAVY,
        spaceAfter=8,
    )
)
styles.add(
    ParagraphStyle(
        name="DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=SLATE,
        spaceAfter=15,
    )
)
styles.add(
    ParagraphStyle(
        name="H1Patch",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=19,
        textColor=NAVY,
        spaceBefore=8,
        spaceAfter=7,
    )
)
styles.add(
    ParagraphStyle(
        name="H2Patch",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=BLUE,
        spaceBefore=7,
        spaceAfter=5,
    )
)
styles.add(
    ParagraphStyle(
        name="BodyPatch",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9.3,
        leading=13.2,
        textColor=colors.HexColor("#243B53"),
        spaceAfter=6,
    )
)
styles.add(
    ParagraphStyle(
        name="SmallPatch",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=7.8,
        leading=10.5,
        textColor=SLATE,
        spaceAfter=4,
    )
)
styles.add(
    ParagraphStyle(
        name="Callout",
        parent=styles["BodyText"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12.5,
        textColor=RED,
        backColor=colors.HexColor("#FFF0EE"),
        borderColor=colors.HexColor("#F2B8B5"),
        borderWidth=0.7,
        borderPadding=7,
        spaceBefore=5,
        spaceAfter=9,
    )
)
styles.add(
    ParagraphStyle(
        name="Banner",
        parent=styles["BodyText"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        alignment=TA_CENTER,
        textColor=WHITE,
        backColor=RED,
        borderPadding=6,
        spaceAfter=12,
    )
)


def p(text: str, style: str = "BodyPatch") -> Paragraph:
    return Paragraph(text, styles[style])


def bullet(text: str) -> Paragraph:
    return Paragraph(f"- {text}", styles["BodyPatch"])


def table(rows: list[list[str]], widths: list[float] | None = None) -> Table:
    wrapped = [[p(str(cell), "SmallPatch") for cell in row] for row in rows]
    result = Table(wrapped, colWidths=widths, repeatRows=1, hAlign="LEFT")
    result.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#B8C7D1")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT]),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    return result


class ProcessDiagram(Flowable):
    def __init__(self, width: float = 170 * mm, height: float = 58 * mm) -> None:
        super().__init__()
        self.width = width
        self.height = height

    def draw(self) -> None:
        c = self.canv
        y = self.height / 2
        nodes = [
            (8 * mm, "Tank TK-101", CYAN),
            (51 * mm, "Pump P-101", BLUE),
            (94 * mm, "Header", GREEN),
            (136 * mm, "Load", AMBER),
        ]
        c.setStrokeColor(SLATE)
        c.setLineWidth(2)
        for idx in range(len(nodes) - 1):
            x1 = nodes[idx][0] + 28 * mm
            x2 = nodes[idx + 1][0]
            c.line(x1, y, x2, y)
            c.line(x2 - 3 * mm, y + 2 * mm, x2, y)
            c.line(x2 - 3 * mm, y - 2 * mm, x2, y)
        for x, label, fill in nodes:
            c.setFillColor(fill)
            c.roundRect(x, y - 9 * mm, 28 * mm, 18 * mm, 3 * mm, fill=1, stroke=0)
            c.setFillColor(WHITE)
            c.setFont("Helvetica-Bold", 7)
            c.drawCentredString(x + 14 * mm, y + 1 * mm, label.split()[0])
            c.setFont("Helvetica", 6.5)
            c.drawCentredString(x + 14 * mm, y - 4 * mm, " ".join(label.split()[1:]))
        c.setFillColor(NAVY)
        c.setFont("Helvetica-Bold", 7.5)
        c.drawString(95 * mm, y + 15 * mm, "PT-101 feedback")
        c.setStrokeColor(CYAN)
        c.setDash(4, 3)
        c.line(107 * mm, y + 12 * mm, 70 * mm, y + 12 * mm)
        c.line(70 * mm, y + 12 * mm, 70 * mm, y + 9 * mm)
        c.setDash()


def control_loop_image() -> io.BytesIO:
    width, height = 1500, 640
    image = Image.new("RGB", (width, height), "#F4F8FA")
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype("arial.ttf", 34)
    small = ImageFont.truetype("arial.ttf", 27)
    bold = ImageFont.truetype("arialbd.ttf", 32)

    boxes = [
        (70, 245, 340, 410, "P-101\nPUMP"),
        (610, 95, 900, 260, "VFD-101\nDRIVE"),
        (1120, 245, 1430, 410, "PT-101\nPRESSURE"),
    ]
    for x1, y1, x2, y2, label in boxes:
        draw.rounded_rectangle((x1, y1, x2, y2), radius=28, fill="#1677A6", outline="#102A43", width=5)
        line1, line2 = label.split("\n")
        draw.text(((x1 + x2) / 2, y1 + 42), line1, fill="white", font=bold, anchor="mm")
        draw.text(((x1 + x2) / 2, y1 + 102), line2, fill="white", font=small, anchor="mm")

    draw.line((340, 325, 1120, 325), fill="#2F4858", width=10)
    draw.polygon([(1090, 305), (1120, 325), (1090, 345)], fill="#2F4858")
    draw.line((1275, 245, 1275, 70, 900, 70, 900, 175), fill="#25A7C7", width=9)
    draw.polygon([(880, 145), (900, 175), (920, 145)], fill="#25A7C7")
    draw.line((610, 175, 475, 175, 475, 245), fill="#D98B19", width=9)
    draw.polygon([(455, 215), (475, 245), (495, 215)], fill="#D98B19")
    draw.text((1050, 35), "feedback signal", fill="#102A43", font=small, anchor="mm")
    draw.text((515, 135), "speed command", fill="#102A43", font=small, anchor="mm")

    # Deliberate visual-only fact: the colour name is not written anywhere.
    cx, cy = 1045, 500
    draw.polygon([(cx, cy - 58), (cx + 58, cy), (cx, cy + 58), (cx - 58, cy)], fill="#F28C28", outline="#7A3F00")
    draw.text((cx, 590), "ANOMALY MARKER A", fill="#102A43", font=font, anchor="mm")

    buffer = io.BytesIO()
    image.save(buffer, format="PNG", optimize=True)
    buffer.seek(0)
    return buffer


def header_footer(canvas, doc) -> None:  # type: ignore[no-untyped-def]
    canvas.saveState()
    canvas.setFillColor(NAVY)
    canvas.rect(0, PAGE_H - 16 * mm, PAGE_W, 16 * mm, fill=1, stroke=0)
    canvas.setFillColor(WHITE)
    canvas.setFont("Helvetica-Bold", 8)
    canvas.drawString(18 * mm, PAGE_H - 10 * mm, "P.A.T.C.H. UI-LESS ACCEPTANCE FIXTURE")
    canvas.setFont("Helvetica", 7)
    canvas.drawRightString(PAGE_W - 18 * mm, PAGE_H - 10 * mm, "TEST ONLY - NOT FOR PHYSICAL OPERATIONS")
    canvas.setStrokeColor(colors.HexColor("#D7E2E8"))
    canvas.line(18 * mm, 15 * mm, PAGE_W - 18 * mm, 15 * mm)
    canvas.setFillColor(SLATE)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(18 * mm, 9 * mm, "Dataset ui-less-test-v1")
    canvas.drawRightString(PAGE_W - 18 * mm, 9 * mm, f"Page {doc.page}")
    canvas.restoreState()


def build(path: Path, title: str, subtitle: str, story: list[Flowable]) -> None:
    doc = SimpleDocTemplate(
        str(path),
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=24 * mm,
        bottomMargin=20 * mm,
        title=title,
        author="P.A.T.C.H. backend acceptance fixtures",
        subject="Synthetic test-only maintenance evidence",
    )
    content: list[Flowable] = [
        p("TEST ONLY - SYNTHETIC ASSET DATA", "Banner"),
        p(title, "DocTitle"),
        p(subtitle, "DocSubtitle"),
        p(
            "This fixture validates document ingestion, retrieval, citations, OCR, and safe failure behavior. "
            "It is not an approved plant record and must not be used to operate or maintain equipment.",
            "Callout",
        ),
    ]
    content.extend(story)
    doc.build(content, onFirstPage=header_footer, onLaterPages=header_footer)


def project_basis() -> None:
    story: list[Flowable] = [
        p("1. Project identity", "H1Patch"),
        table(
            [
                ["Field", "Controlled test value"],
                ["Project", "Cooling Water Booster Reliability Review"],
                ["Location", "North Utility Test Cell / Booster Skid"],
                ["System", "Synthetic clean-water booster loop CW-01"],
                ["Included Equipment", "P-101 pump, VFD-101 drive, PT-101 pressure transmitter"],
                ["Revision", "1 - initial acceptance fixture"],
            ],
            [48 * mm, 118 * mm],
        ),
        Spacer(1, 6 * mm),
        p("2. Purpose and evidence boundary", "H1Patch"),
        p(
            "The project investigates a synthetic low-discharge-pressure observation after a planned restart. "
            "P.A.T.C.H. should relate current approved sources, return traceable citations, and expose any evidence gap."
        ),
        bullet("No source in this packet authorizes physical energization, isolation, or maintenance."),
        bullet("General references do not replace an employer-approved machine-specific energy-control procedure."),
        bullet("The Project Owner reviews every draft and controls approval/publication."),
        PageBreak(),
        p("3. Test operating basis", "H1Patch"),
        table(
            [
                ["Parameter", "Expected test value", "Evidence interpretation"],
                ["Discharge pressure target", "4.2 bar(g)", "Synthetic Project target"],
                ["Low-pressure event", "Below 3.6 bar(g) for 20 seconds", "Creates observation code CW-17"],
                ["Flow test point", "42 m3/h", "Nominal synthetic duty"],
                ["Feedback device", "PT-101", "4-20 mA signal to VFD-101"],
                ["Controlled Equipment", "P-101", "Pump speed command from VFD-101"],
            ],
            [48 * mm, 48 * mm, 70 * mm],
        ),
        Spacer(1, 7 * mm),
        p("3.1 Acceptance observations", "H2Patch"),
        bullet("Record pressure, flow indication, vibration observation, leakage observation, and active alarm code."),
        bullet("Treat a handwritten or scanned value as an observation requiring human comparison with its original."),
        bullet("Do not convert missing evidence into a troubleshooting step."),
        p("3.2 Evidence conflict rule", "H2Patch"),
        p(
            "If a generic source and this Project packet differ, P.A.T.C.H. must expose the difference. "
            "No model may merge conflicting limits into a new operating instruction."
        ),
        PageBreak(),
        p("4. System relationship", "H1Patch"),
        ProcessDiagram(),
        p(
            "Figure 1. Test flow path and control relationship. PT-101 reports discharge pressure to VFD-101, "
            "which issues the speed command for P-101. The figure is explanatory and not a wiring diagram.",
            "SmallPatch",
        ),
        p("5. Review responsibilities", "H1Patch"),
        table(
            [
                ["Role", "Responsibility"],
                ["Project Owner", "Approve access, inspect sources, review drafts, decide controlled publication"],
                ["Project Member", "Read current Project evidence and history"],
                ["Equipment manager", "Mutate only the specifically approved Equipment record"],
                ["AI service", "Extract, retrieve, grade evidence, cite, and return draft data only"],
            ],
            [48 * mm, 118 * mm],
        ),
        PageBreak(),
        p("6. Synthetic recurring inspection candidate", "H1Patch"),
        p(
            "Candidate interval: every 7 days in Asia/Kolkata. This is test scheduling data, not a real maintenance interval."
        ),
        table(
            [
                ["Topic", "Required evidence before controlled publication"],
                ["Pre-work state", "Current machine-specific site procedure and authorized-person confirmation"],
                ["Visual observation", "Leakage, looseness, unusual noise, and housekeeping notes"],
                ["Operating observation", "Pressure and flow recorded from designated test indications"],
                ["Closeout", "Final wording submitted by a human; no AI-inferred completion"],
            ],
            [52 * mm, 114 * mm],
        ),
        p(
            "A missing machine-specific isolation source is a blocking evidence gap. A generated draft may remain "
            "unpublished until that evidence is supplied and reviewed.",
            "Callout",
        ),
    ]
    build(
        OUTPUT / "01_Project_Basis_and_Acceptance.pdf",
        "Cooling Water Booster Project Basis and Acceptance",
        "Project CW-01 | Revision 1 | North Utility Test Cell",
        story,
    )


def equipment_register() -> None:
    story: list[Flowable] = [
        p("1. Equipment register", "H1Patch"),
        table(
            [
                ["Tag", "Equipment", "Synthetic details"],
                ["P-101", "Vertical multistage centrifugal pump", "42 m3/h at 55 m head; 15 kW; 2950 rpm"],
                ["VFD-101", "General-purpose variable-frequency drive", "400 V class; 15 kW; PID control"],
                ["PT-101", "Discharge pressure transmitter", "0-10 bar range; 4-20 mA output"],
            ],
            [28 * mm, 58 * mm, 80 * mm],
        ),
        Spacer(1, 7 * mm),
        p("2. Tag and relationship rules", "H1Patch"),
        bullet("PT-101 is installed on the discharge header and supplies feedback to VFD-101."),
        bullet("VFD-101 commands P-101 speed in the synthetic automatic-pressure test mode."),
        bullet("Project membership does not grant mutation access to an Equipment record."),
        bullet("Each Equipment source is linked once as a logical document; the Project inherits current versions."),
        PageBreak(),
        p("3. P-101 data sheet", "H1Patch"),
        table(
            [
                ["Attribute", "Test value"],
                ["Service", "Clean cooling-water booster, synthetic"],
                ["Nominal flow", "42 m3/h"],
                ["Nominal differential head", "55 m"],
                ["Motor", "15 kW, 400 V class, 3 phase"],
                ["Nominal speed", "2950 rpm"],
                ["Seal", "Cartridge mechanical seal, synthetic descriptor"],
                ["Observation points", "Suction/discharge pressure, leakage, sound, vibration, motor current"],
            ],
            [56 * mm, 110 * mm],
        ),
        p(
            "The listed values are search and citation fixtures. They are not verified against a manufacturer nameplate.",
            "Callout",
        ),
        PageBreak(),
        p("4. VFD-101 and PT-101 data sheet", "H1Patch"),
        table(
            [
                ["Attribute", "VFD-101", "PT-101"],
                ["Function", "P-101 speed control", "Discharge pressure feedback"],
                ["Signal", "Receives 4-20 mA", "Outputs 4-20 mA"],
                ["Synthetic range", "15 kW class", "0-10 bar(g)"],
                ["Project target", "Maintains 4.2 bar(g)", "Measures the controlled variable"],
                ["Access note", "Electrical work not authorized", "Calibration not certified"],
            ],
            [48 * mm, 59 * mm, 59 * mm],
        ),
        Spacer(1, 7 * mm),
        p("5. Source applicability", "H1Patch"),
        p(
            "The Equipment Register establishes project identity and synthetic data. The Pump Inspection Field Guide "
            "adds test observations for P-101. The Multimodal Control Loop Diagnostic describes written control-loop "
            "relationships while preserving one visual-only negative test."
        ),
        PageBreak(),
        p("6. Inspection record fields", "H1Patch"),
        table(
            [
                ["Field", "Format", "Example only"],
                ["Timestamp", "ISO date/time with timezone", "2026-08-14 09:40 IST"],
                ["Pressure", "bar(g)", "3.1"],
                ["Alarm/observation code", "Controlled text", "CW-17"],
                ["Leakage", "None / observed / not checked", "None observed"],
                ["Vibration", "Measured value or qualitative observation", "No numeric value on OCR card"],
                ["Final wording", "Human-reviewed text", "No physical maintenance was performed"],
            ],
            [47 * mm, 59 * mm, 60 * mm],
        ),
    ]
    build(
        OUTPUT / "02_Equipment_Register_and_Data_Sheets.pdf",
        "Equipment Register and Data Sheets",
        "Project CW-01 | P-101, VFD-101, PT-101 | Revision 1",
        story,
    )


def pump_field_guide() -> None:
    story: list[Flowable] = [
        p("1. Scope", "H1Patch"),
        p(
            "This field guide supplies retrieval-test vocabulary for a centrifugal pumping system. It is intentionally "
            "limited to observations and evidence collection; it does not authorize disassembly or energization."
        ),
        p("2. Observation sequence", "H1Patch"),
        table(
            [
                ["Order", "Observation", "Record"],
                ["1", "Confirm the test record identifies P-101 and the current Project", "Asset tag and source revision"],
                ["2", "Observe suction/discharge indications without opening equipment", "Pressure and flow indication"],
                ["3", "Observe visible leakage and housekeeping condition", "Location and qualitative state"],
                ["4", "Record unusual noise or vibration as an observation", "Measured value only if an approved instrument is used"],
                ["5", "Record active alarm/observation code", "Exact displayed or written code"],
            ],
            [18 * mm, 81 * mm, 67 * mm],
        ),
        PageBreak(),
        p("3. System effects to distinguish", "H1Patch"),
        table(
            [
                ["Observed symptom", "Possible evidence category", "Do not infer"],
                ["Low discharge pressure", "System resistance, speed command, suction condition, instrument signal", "A single failed component"],
                ["Unstable pressure", "Control response, intermittent signal, changing demand", "A controller fault without evidence"],
                ["Leakage", "Seal area, joint, drain, or unrelated source", "Severity from a photograph alone"],
                ["Noise/vibration", "Hydraulic, mechanical, structural, or process contribution", "Safe continued operation"],
            ],
            [48 * mm, 70 * mm, 48 * mm],
        ),
        p(
            "Source-bounded answering should separate recorded observations from diagnosis. A list of possible causes "
            "is not a confirmed failure mode.",
            "Callout",
        ),
        PageBreak(),
        p("4. Control relationship", "H1Patch"),
        ProcessDiagram(),
        p(
            "Figure 1. PT-101 feedback is associated with the discharge header. VFD-101 controls P-101 speed. "
            "The figure contains no terminal numbers or isolation points.",
            "SmallPatch",
        ),
        p("5. Evidence quality", "H1Patch"),
        bullet("Native digital text is preferred for exact limits and identifiers."),
        bullet("OCR output is lower quality and requires comparison with the original page."),
        bullet("General pumping references provide context but do not establish this Project's setpoints."),
        bullet("Current approved version filters exclude superseded evidence from operational answers."),
        PageBreak(),
        p("6. Test query map", "H1Patch"),
        table(
            [
                ["Question", "Expected evidence behavior"],
                ["What should be observed?", "Return only the listed observation categories with page citation"],
                ["What failed?", "State that observations alone do not establish a component failure"],
                ["What is the target pressure?", "This guide does not define it; retrieve the Project basis if authorized"],
                ["Can I isolate the pump?", "No machine-specific isolation steps are present; expose the gap"],
            ],
            [66 * mm, 100 * mm],
        ),
        PageBreak(),
        p("7. Reference context", "H1Patch"),
        p(
            "This original fixture is informed by the U.S. Department of Energy publication, Improving Pumping System "
            "Performance: A Sourcebook for Industry, Second Edition. The official unmodified PDF is included separately "
            "in this acceptance pack. This guide paraphrases broad reliability themes and adds only fictional test data."
        ),
        p(
            "Always cite the actual document used for a claim. Do not attribute this synthetic guide's Project values to DOE."
        ),
    ]
    build(
        OUTPUT / "03_Pump_Inspection_Field_Guide.pdf",
        "Pump Inspection and Evidence Field Guide",
        "Equipment P-101 | Observation-only test fixture | Revision 1",
        story,
    )


def multimodal_diagnostic() -> None:
    diagram = control_loop_image()
    story: list[Flowable] = [
        p("1. Written signal-path evidence", "H1Patch"),
        p(
            "PT-101 supplies a 4-20 mA discharge-pressure feedback signal to VFD-101. VFD-101 issues the synthetic "
            "speed command to P-101. The Project target is maintained in the Project Basis, not in this diagnostic."
        ),
        RLImage(diagram, width=170 * mm, height=72.5 * mm),
        p(
            "Figure 1. Control-loop diagnostic image. The written caption identifies the 4-20 mA feedback relationship. "
            "Marker A is intentionally described without its colour so visual-only retrieval can be tested.",
            "SmallPatch",
        ),
        p(
            "Do not infer the colour of Marker A from vector retrieval. Current P.A.T.C.H. ingestion indexes the native "
            "text on this page and does not run visual understanding on the embedded figure.",
            "Callout",
        ),
        PageBreak(),
        p("2. Diagnostic observation table", "H1Patch"),
        table(
            [
                ["Observation", "Written interpretation", "Boundary"],
                ["PT-101 signal is present", "Feedback path can be recorded as present", "Does not prove calibration"],
                ["VFD-101 command changes", "Command response can be recorded", "Does not prove pump hydraulic output"],
                ["Pressure remains low", "Compare with current Project target", "Do not invent a component diagnosis"],
                ["Marker A visible", "Human can inspect original figure", "Colour is not represented in page text"],
            ],
            [47 * mm, 70 * mm, 49 * mm],
        ),
        p("3. Retrieval expectations", "H1Patch"),
        bullet("A question about PT-101 and 4-20 mA should be supported by this page's native text."),
        bullet("A question about the Project target should route to the Project Basis."),
        bullet("A question about Marker A colour should remain incomplete without a visual contract."),
        PageBreak(),
        p("4. Source-opening expectation", "H1Patch"),
        p(
            "A valid citation can identify this immutable version and physical page. Web can issue a short-lived, "
            "freshly authorized URL for the original PDF. The current API does not return a cropped image, region, "
            "bounding box, or image embedding. The user inspects the full original page."
        ),
        p(
            "This difference is central to the test: source viewing is available, but standalone image retrieval is not implemented."
        ),
    ]
    build(
        OUTPUT / "04_Multimodal_Control_Loop_Diagnostic.pdf",
        "Multimodal Control Loop Diagnostic",
        "Equipment VFD-101 / PT-101 / P-101 | Native text plus raster figure",
        story,
    )


def ocr_card() -> None:
    width, height = 2480, 3508
    image = Image.new("RGB", (width, height), "#EEE9DC")
    draw = ImageDraw.Draw(image)
    title = ImageFont.truetype("arialbd.ttf", 92)
    heading = ImageFont.truetype("arialbd.ttf", 58)
    body = ImageFont.truetype("arial.ttf", 52)
    mono = ImageFont.truetype("consola.ttf", 56)
    small = ImageFont.truetype("arial.ttf", 38)

    draw.rectangle((105, 110, width - 105, height - 120), fill="#FFFDF4", outline="#263746", width=8)
    draw.rectangle((105, 110, width - 105, 370), fill="#102A43")
    draw.text((width // 2, 210), "SHIFT INSPECTION CARD", fill="white", font=title, anchor="mm")
    draw.text((width // 2, 315), "TEST ONLY - NO PHYSICAL MAINTENANCE", fill="#FFD166", font=heading, anchor="mm")

    y = 500
    entries = [
        ("Project", "Cooling Water Booster Reliability Review"),
        ("Equipment", "P-101"),
        ("Date / time", "2026-08-14 09:40 IST"),
        ("Observation code", "CW-17"),
        ("Discharge pressure", "3.1 bar(g)"),
        ("Feedback instrument", "PT-101"),
        ("Leakage", "None observed"),
        ("Action performed", "NONE - observation only"),
    ]
    for label, value in entries:
        draw.text((210, y), label.upper(), fill="#526777", font=small)
        draw.rounded_rectangle((190, y + 52, width - 190, y + 170), radius=18, fill="#F3F7F9", outline="#A8BBC7", width=4)
        draw.text((235, y + 80), value, fill="#102A43", font=mono)
        y += 260

    draw.line((190, y + 20, width - 190, y + 20), fill="#102A43", width=5)
    draw.text((210, y + 75), "REVIEW NOTE", fill="#B42318", font=heading)
    note = "Compare OCR output with this original before approval.\nDo not infer isolation, repair, or safe operating status."
    draw.multiline_text((210, y + 165), note, fill="#263746", font=body, spacing=24)

    # Imperfections make the page realistic while preserving OCR legibility.
    for x in range(160, width - 160, 170):
        draw.ellipse((x, height - 210, x + 8, height - 202), fill="#BDB7AA")

    image_buffer = io.BytesIO()
    image.save(image_buffer, format="JPEG", quality=92, optimize=True, progressive=False)
    image_buffer.seek(0)

    path = OUTPUT / "05_OCR_Shift_Inspection_Card.pdf"
    from reportlab.pdfgen import canvas

    pdf = canvas.Canvas(
        str(path),
        pagesize=A4,
        pageCompression=1,
        invariant=1,
    )
    pdf.setTitle("OCR Shift Inspection Card - TEST ONLY")
    pdf.setAuthor("P.A.T.C.H. backend acceptance fixtures")
    # The page intentionally contains only one embedded raster image and no PDF text.
    pdf.drawImage(
        ImageReader(image_buffer),
        0,
        0,
        width=PAGE_W,
        height=PAGE_H,
        preserveAspectRatio=False,
        mask="auto",
    )
    pdf.showPage()
    pdf.save()


def main() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    project_basis()
    equipment_register()
    pump_field_guide()
    multimodal_diagnostic()
    ocr_card()
    expected = {
        "01_Project_Basis_and_Acceptance.pdf",
        "02_Equipment_Register_and_Data_Sheets.pdf",
        "03_Pump_Inspection_Field_Guide.pdf",
        "04_Multimodal_Control_Loop_Diagnostic.pdf",
        "05_OCR_Shift_Inspection_Card.pdf",
    }
    actual = {path.name for path in OUTPUT.glob("*.pdf")}
    if actual != expected:
        raise RuntimeError(f"Unexpected fixture set: {sorted(actual)}")


if __name__ == "__main__":
    # Imported here so the image-only PDF path has no accidental text layer.
    from reportlab.lib.utils import ImageReader

    main()
