/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Process liveness. This endpoint intentionally does not inspect dependencies.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readiness": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness
     * @description Aggregate runtime readiness without exposing configuration names or values.
     */
    get: operations["readiness_readiness_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/entity-profiles/upsert": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upsert Entity Profile */
    post: operations["upsert_entity_profile_v1_entity_profiles_upsert_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/ingestions/delete-vectors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Delete Vectors */
    post: operations["delete_vectors_v1_ingestions_delete_vectors_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/ingestions/extract": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Extract Document */
    post: operations["extract_document_v1_ingestions_extract_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/ingestions/index": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Index Document */
    post: operations["index_document_v1_ingestions_index_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/log-drafts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Draft Log */
    post: operations["draft_log_v1_log_drafts_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/procedure-drafts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Draft Procedure */
    post: operations["draft_procedure_v1_procedure_drafts_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/procedure-drafts/revalidate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revalidate Procedure */
    post: operations["revalidate_procedure_v1_procedure_drafts_revalidate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/questions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Answer Question */
    post: operations["answer_question_v1_questions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActiveDocument */
    ActiveDocument: {
      /** Documentid */
      documentId: string;
      /** Documentsummary */
      documentSummary: string;
      /** Documentversionid */
      documentVersionId: string;
      /**
       * Inclusion
       * @enum {string}
       */
      inclusion: "EQUIPMENT_DIRECT" | "PROJECT_DIRECT" | "EQUIPMENT_DERIVED";
      /** Title */
      title: string;
    };
    /** Actor */
    Actor: {
      /** Id */
      id: string;
      /** Tenantid */
      tenantId: string;
    };
    /** AllowedDocumentVersion */
    AllowedDocumentVersion: {
      /** Documentid */
      documentId: string;
      /** Documentversionid */
      documentVersionId: string;
      /** Inclusionpaths */
      inclusionPaths: (
        | "PERSONAL"
        | "PROJECT_DIRECT"
        | "EQUIPMENT_DERIVED"
        | "PROJECT_PROCEDURE"
        | "PROJECT_LOG"
      )[];
      /** Sourceentityids */
      sourceEntityIds?: string[];
    };
    /** Answer */
    Answer: {
      /** Steps */
      steps?: components["schemas"]["AnswerStep"][];
      /**
       * Summary
       * @default null
       */
      summary: string | null;
    };
    /** AnswerStep */
    AnswerStep: {
      /** Citationids */
      citationIds: string[];
      /** Id */
      id: string;
      /** Text */
      text: string;
    };
    /** ApiErrorResponse */
    ApiErrorResponse: {
      error: components["schemas"]["ErrorDetail"];
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
    };
    /** AssignedReference */
    AssignedReference: {
      /** Id */
      id: string;
      /**
       * Type
       * @enum {string}
       */
      type: "DOCUMENT" | "EQUIPMENT" | "PROJECT" | "ENTITY";
    };
    /** ChatSessionInput */
    ChatSessionInput: {
      /** Id */
      id: string;
      /** Recentturns */
      recentTurns?: components["schemas"]["ChatTurnContext"][];
    };
    /** ChatSessionResult */
    ChatSessionResult: {
      /** Id */
      id: string;
      /** Suggestedtitle */
      suggestedTitle: string;
    };
    /** ChatTurnContext */
    ChatTurnContext: {
      /** Content */
      content: string;
      /**
       * Role
       * @enum {string}
       */
      role: "user" | "assistant";
    };
    /** Citation */
    Citation: {
      /**
       * Approvalstate
       * @default null
       */
      approvalState: "APPROVED" | null;
      /**
       * Chunkid
       * @default null
       */
      chunkId: string | null;
      /**
       * Documentid
       * @default null
       */
      documentId: string | null;
      /**
       * Documenttitle
       * @default null
       */
      documentTitle: string | null;
      /** Documentversionid */
      documentVersionId: string;
      /** Excerpt */
      excerpt: string;
      /** Id */
      id: string;
      /**
       * Page
       * @default null
       */
      page: number | null;
      /**
       * Revision
       * @default null
       */
      revision: string | null;
      /**
       * Section
       * @default null
       */
      section: string | null;
    };
    /** DeclaredMetadata */
    DeclaredMetadata: {
      /** Documenttype */
      documentType: string;
      /** Title */
      title: string;
    };
    /** DeleteVectorsRequest */
    DeleteVectorsRequest: {
      /**
       * Contractversion
       * @constant
       */
      contractVersion: "v1";
      /** Documentversionid */
      documentVersionId: string;
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      /** Tenantid */
      tenantId: string;
    };
    /** DeleteVectorsResult */
    DeleteVectorsResult: {
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      /**
       * Status
       * @enum {string}
       */
      status: "deleted" | "failed";
    };
    /** DocumentSummary */
    DocumentSummary: {
      /** Capabilities */
      capabilities?: string[];
      /** Searchhints */
      searchHints?: string[];
      /** Summary */
      summary: string;
      /** Systems */
      systems?: string[];
    };
    /** EntityProfileInput */
    EntityProfileInput: {
      /** Activedocuments */
      activeDocuments?: components["schemas"]["ActiveDocument"][];
      /** Id */
      id: string;
      /** Includedequipmentprofiles */
      includedEquipmentProfiles?: components["schemas"]["IncludedEquipmentProfile"][];
      /** Profileversion */
      profileVersion: number;
      /**
       * Type
       * @enum {string}
       */
      type: "EQUIPMENT" | "PROJECT";
      /** Userdescription */
      userDescription?: string | null;
      /** Workflowcoverage */
      workflowCoverage?: string[];
    };
    /** EntityProfileRequest */
    EntityProfileRequest: {
      /**
       * Contractversion
       * @constant
       */
      contractVersion: "v1";
      entity: components["schemas"]["EntityProfileInput"];
      /** Inputfingerprint */
      inputFingerprint: string;
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      /** Tenantid */
      tenantId: string;
    };
    /** EntityProfileResult */
    EntityProfileResult: {
      /** Capabilities */
      capabilities?: string[];
      /** Components */
      components?: string[];
      /** Coverage */
      coverage?: components["schemas"]["ProfileCoverage"][];
      /** Entityid */
      entityId: string;
      /** Errors */
      errors?: components["schemas"]["ServiceError"][];
      /** Failuremodes */
      failureModes?: string[];
      /** Generateddescription */
      generatedDescription: string;
      /** Profilefingerprint */
      profileFingerprint: string;
      /** Profileid */
      profileId: string;
      /** Profileversion */
      profileVersion: number;
      provenance: components["schemas"]["ProfileProvenance"];
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      /** Searchhints */
      searchHints?: string[];
      /**
       * Status
       * @enum {string}
       */
      status: "upserted" | "failed";
      /** Systems */
      systems?: string[];
    };
    /** ErrorDetail */
    ErrorDetail: {
      /** Code */
      code: string;
      /** Fields */
      fields?: string[] | null;
    };
    /** ExtractRequest */
    ExtractRequest: {
      /**
       * Contractversion
       * @constant
       */
      contractVersion: "v1";
      declaredMetadata: components["schemas"]["DeclaredMetadata"];
      /** Documentid */
      documentId: string;
      /** Documentversionid */
      documentVersionId: string;
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      sourceFile: components["schemas"]["SourceFile"];
      /** Versionnumber */
      versionNumber: string;
    };
    /** ExtractResult */
    ExtractResult: {
      documentSummary?: components["schemas"]["DocumentSummary"] | null;
      /** Documentversionid */
      documentVersionId: string;
      /** Errors */
      errors?: components["schemas"]["ServiceError"][];
      extractedMetadata?: components["schemas"]["ExtractedMetadata"] | null;
      /** Extractionquality */
      extractionQuality: number;
      /** Pages */
      pages?: components["schemas"]["ExtractedPage"][];
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      /**
       * Status
       * @enum {string}
       */
      status: "needs_review" | "failed";
    };
    /** ExtractedMetadata */
    ExtractedMetadata: {
      /** Language */
      language?: string | null;
      /** Pagecount */
      pageCount?: number | null;
      /** Sections */
      sections?: string[];
      /** Title */
      title: string;
    };
    /** ExtractedPage */
    ExtractedPage: {
      /** Page */
      page: number;
      /** Quality */
      quality: number;
      /** Section */
      section: string;
      /** Text */
      text: string;
    };
    /** HealthStatus */
    HealthStatus: {
      /**
       * Service
       * @default patch-ai
       * @constant
       */
      service: "patch-ai";
      /**
       * Status
       * @default available
       * @constant
       */
      status: "available";
    };
    /** IncludedEquipmentProfile */
    IncludedEquipmentProfile: {
      /** Coveragetopics */
      coverageTopics?: string[];
      /** Equipmentid */
      equipmentId: string;
      /**
       * Freshnessstate
       * @enum {string}
       */
      freshnessState: "FRESH" | "STALE";
      /** Generateddescription */
      generatedDescription: string;
      /** Profilefingerprint */
      profileFingerprint: string;
      /** Profileid */
      profileId: string;
      /** Profileversion */
      profileVersion: number;
    };
    /** IndexRequest */
    IndexRequest: {
      /**
       * Approvalstate
       * @constant
       */
      approvalState: "APPROVED";
      /**
       * Contractversion
       * @constant
       */
      contractVersion: "v1";
      /** Documentid */
      documentId: string;
      /** Documentversionid */
      documentVersionId: string;
      /** Originalfileid */
      originalFileId: string;
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      reviewedMetadata: components["schemas"]["ReviewedMetadata"];
      sourceFile: components["schemas"]["SourceFile"];
      /** Tenantid */
      tenantId: string;
    };
    /** IndexResult */
    IndexResult: {
      /** Chunkcount */
      chunkCount: number;
      /** Contentfingerprint */
      contentFingerprint?: string | null;
      /** Documentversionid */
      documentVersionId: string;
      /** Errors */
      errors?: components["schemas"]["ServiceError"][];
      /** Indexreference */
      indexReference?: string | null;
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      /** Sourcelocations */
      sourceLocations?: components["schemas"]["SourceLocation"][];
      /**
       * Status
       * @enum {string}
       */
      status: "indexed" | "failed";
    };
    /** LogDraftRequest */
    LogDraftRequest: {
      /** Citationids */
      citationIds?: string[];
      /**
       * Contractversion
       * @constant
       */
      contractVersion: "v1";
      /** Equipmentid */
      equipmentId?: string | null;
      /** Projectid */
      projectId: string;
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      scopeType: components["schemas"]["LogScope"];
      /** Sourcetext */
      sourceText: string;
    };
    /** LogDraftResult */
    LogDraftResult: {
      /** Citationids */
      citationIds?: string[];
      /** Drafttext */
      draftText?: string | null;
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      /**
       * Status
       * @enum {string}
       */
      status: "drafted" | "unavailable";
      /** Suggestedfields */
      suggestedFields?: {
        [key: string]: string;
      };
      /** Warnings */
      warnings?: string[];
    };
    /**
     * LogScope
     * @enum {string}
     */
    LogScope: "PROJECT" | "EQUIPMENT";
    /** ManifestEntity */
    ManifestEntity: {
      /** Directdocumentversionids */
      directDocumentVersionIds?: string[];
      /** Id */
      id: string;
      /** Profileid */
      profileId?: string | null;
      /**
       * Profilestate
       * @enum {string}
       */
      profileState: "FRESH" | "STALE" | "MISSING";
      /** Profileversion */
      profileVersion?: number | null;
      /**
       * Type
       * @enum {string}
       */
      type: "EQUIPMENT" | "PROJECT";
    };
    /** ManifestRelationship */
    ManifestRelationship: {
      /** Directdocumentversionids */
      directDocumentVersionIds?: string[];
      /** Equipmentids */
      equipmentIds?: string[];
      /** Projectid */
      projectId: string;
    };
    /** ProcedureDraftRequest */
    ProcedureDraftRequest: {
      /** Activesources */
      activeSources: components["schemas"]["ProcedureSource"][];
      /**
       * Contractversion
       * @constant
       */
      contractVersion: "v1";
      /** Generationrequestid */
      generationRequestId: string;
      /** Inputfingerprint */
      inputFingerprint: string;
      /** Projectdescription */
      projectDescription: string;
      /** Projectid */
      projectId: string;
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      retrievalScopeManifest: components["schemas"]["RetrievalScopeManifest"];
      /** Supplementalequipmentsources */
      supplementalEquipmentSources?: components["schemas"]["SupplementalEquipmentSource"][];
      /** Tenantid */
      tenantId: string;
      /** Timezone */
      timezone: string;
    };
    /** ProcedureDraftResult */
    ProcedureDraftResult: {
      /** Citations */
      citations?: components["schemas"]["Citation"][];
      /** Generationrequestid */
      generationRequestId: string;
      /** Inputfingerprint */
      inputFingerprint: string;
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      /**
       * Requireshumanreview
       * @default true
       * @constant
       */
      requiresHumanReview: true;
      reviewAnalysis: components["schemas"]["ReviewAnalysis"];
      /**
       * Status
       * @enum {string}
       */
      status: "generated" | "unavailable";
      /** Steps */
      steps?: components["schemas"]["ProcedureStep"][];
      /** Title */
      title?: string | null;
    };
    /** ProcedureSource */
    ProcedureSource: {
      /** Documenttitle */
      documentTitle: string;
      /** Documentversionid */
      documentVersionId: string;
      /**
       * Inclusionpath
       * @constant
       */
      inclusionPath: "PROJECT_DIRECT";
      /** Revision */
      revision: string;
    };
    /** ProcedureStep */
    ProcedureStep: {
      /** Citationids */
      citationIds: string[];
      /** Evidencestate */
      evidenceState: string;
      /** Instructions */
      instructions: string;
      /** Position */
      position: number;
      /** Required */
      required: boolean;
      /** Stepid */
      stepId: string;
      /** Title */
      title: string;
    };
    /** ProfileCoverage */
    ProfileCoverage: {
      /** Documentversionids */
      documentVersionIds: string[];
      /** Topic */
      topic: string;
    };
    /** ProfileProvenance */
    ProfileProvenance: {
      /** Documentversionids */
      documentVersionIds?: string[];
      /** Includedequipmentprofilefingerprints */
      includedEquipmentProfileFingerprints?: string[];
      /** Inputfingerprint */
      inputFingerprint: string;
      /** Tenantid */
      tenantId: string;
    };
    /** QuestionRequest */
    QuestionRequest: {
      actor: components["schemas"]["Actor"];
      /** Assignedreferences */
      assignedReferences?: components["schemas"]["AssignedReference"][];
      chatSession: components["schemas"]["ChatSessionInput"];
      /**
       * Contractversion
       * @constant
       */
      contractVersion: "v1";
      /** Question */
      question: string;
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      retrievalPolicy: components["schemas"]["RetrievalPolicy"];
      retrievalScopeManifest: components["schemas"]["RetrievalScopeManifest"];
    };
    /** QuestionResult */
    QuestionResult: {
      answer: components["schemas"]["Answer"];
      chatSession: components["schemas"]["ChatSessionResult"];
      /** Citations */
      citations?: components["schemas"]["Citation"][];
      /** Followupallowed */
      followUpAllowed: boolean;
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      routing: components["schemas"]["RoutingResult"];
      /**
       * Status
       * @enum {string}
       */
      status:
        "approved" | "incomplete" | "conflicting" | "outdated" | "unavailable";
      /** Turnid */
      turnId: string;
      /** Warnings */
      warnings?: string[];
    };
    /** QuestionSocketEvent */
    QuestionSocketEvent: {
      /**
       * Code
       * @default null
       */
      code: string | null;
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      /** @default null */
      result: components["schemas"]["QuestionResult"] | null;
      /**
       * Stage
       * @default null
       */
      stage: ("retrieving" | "verifying") | null;
      /**
       * Type
       * @enum {string}
       */
      type: "question.progress" | "question.result" | "question.error";
    };
    /** ReadinessStatus */
    ReadinessStatus: {
      /**
       * Service
       * @default patch-ai
       * @constant
       */
      service: "patch-ai";
      /**
       * Status
       * @enum {string}
       */
      status: "ready" | "unavailable";
    };
    /** RetrievalPolicy */
    RetrievalPolicy: {
      /**
       * Allowstructuralfallback
       * @default true
       */
      allowStructuralFallback: boolean;
      /**
       * Approvedonly
       * @default true
       * @constant
       */
      approvedOnly: true;
      /**
       * Requiresourcelocation
       * @default true
       * @constant
       */
      requireSourceLocation: true;
    };
    /** RetrievalScopeManifest */
    RetrievalScopeManifest: {
      /** Alloweddocumentversions */
      allowedDocumentVersions?: components["schemas"]["AllowedDocumentVersion"][];
      /** Entities */
      entities?: components["schemas"]["ManifestEntity"][];
      /** Relationships */
      relationships?: components["schemas"]["ManifestRelationship"][];
    };
    /** RevalidationRequest */
    RevalidationRequest: {
      /** Activesources */
      activeSources: components["schemas"]["ProcedureSource"][];
      /**
       * Contractversion
       * @constant
       */
      contractVersion: "v1";
      /** Generationrequestid */
      generationRequestId: string;
      /** Inputfingerprint */
      inputFingerprint: string;
      /** Projectdescription */
      projectDescription: string;
      /** Projectid */
      projectId: string;
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      retrievalScopeManifest: components["schemas"]["RetrievalScopeManifest"];
      /** Steps */
      steps: components["schemas"]["ProcedureStep"][];
      /** Supplementalequipmentsources */
      supplementalEquipmentSources?: components["schemas"]["SupplementalEquipmentSource"][];
      /** Tenantid */
      tenantId: string;
      /** Timezone */
      timezone: string;
    };
    /** RevalidationResult */
    RevalidationResult: {
      /** Citations */
      citations?: components["schemas"]["Citation"][];
      /**
       * Requestid
       * Format: uuid
       */
      requestId: string;
      reviewAnalysis: components["schemas"]["ReviewAnalysis"];
      /**
       * Status
       * @enum {string}
       */
      status: "validated" | "needs_review" | "unavailable";
      /** Stepcitations */
      stepCitations?: components["schemas"]["StepCitationBinding"][];
      /** Supportedstepids */
      supportedStepIds?: string[];
    };
    /** ReviewAnalysis */
    ReviewAnalysis: {
      /**
       * Applicability
       * @default UNKNOWN
       */
      applicability: string;
      /** Blockingfindings */
      blockingFindings?: string[];
      /** Conflicts */
      conflicts: string;
      /** Freshness */
      freshness: string;
      /** Hardwarecriticality */
      hardwareCriticality: string;
      /** Missingtopics */
      missingTopics?: string[];
      /** Reasons */
      reasons?: string[];
      /** Requiredtopics */
      requiredTopics?: string[];
      /**
       * Reviewneed
       * @enum {string}
       */
      reviewNeed: "LOW" | "MODERATE" | "HIGH" | "SEVERE";
      /** Sourcecoverage */
      sourceCoverage: string;
    };
    /** ReviewedMetadata */
    ReviewedMetadata: {
      /**
       * Documenttype
       * @default MANUAL
       */
      documentType: string;
      /** Revision */
      revision: string;
      /** Title */
      title: string;
    };
    /** RoutedEntity */
    RoutedEntity: {
      /** Id */
      id: string;
      /** Reason */
      reason: string;
      /**
       * Type
       * @enum {string}
       */
      type: "EQUIPMENT" | "PROJECT";
    };
    /** RoutingResult */
    RoutingResult: {
      /** Profileversions */
      profileVersions?: number[];
      /** Selectedentities */
      selectedEntities?: components["schemas"]["RoutedEntity"][];
      /** Usedstructuralfallback */
      usedStructuralFallback: boolean;
    };
    /** ServiceError */
    ServiceError: {
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /** SourceFile */
    SourceFile: {
      /** Contenttype */
      contentType: string;
      /** Sha256 */
      sha256: string;
      /**
       * Url
       * Format: uri
       */
      url: string;
    };
    /** SourceLocation */
    SourceLocation: {
      /** Page */
      page?: number | null;
      /** Section */
      section?: string | null;
    };
    /** StepCitationBinding */
    StepCitationBinding: {
      /** Citationids */
      citationIds: string[];
      /** Stepid */
      stepId: string;
    };
    /** SupplementalEquipmentSource */
    SupplementalEquipmentSource: {
      /** Applicability */
      applicability: string;
      /** Documentversionid */
      documentVersionId: string;
      /** Equipmentid */
      equipmentId: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthStatus"];
        };
      };
    };
  };
  readiness_readiness_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessStatus"];
        };
      };
      /** @description Request correlation mismatch. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request ID replay detected. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request schema validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  upsert_entity_profile_v1_entity_profiles_upsert_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EntityProfileRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntityProfileResult"];
        };
      };
      /** @description Request correlation mismatch. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request ID replay detected. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request schema validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  delete_vectors_v1_ingestions_delete_vectors_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteVectorsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeleteVectorsResult"];
        };
      };
      /** @description Request correlation mismatch. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request ID replay detected. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request schema validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  extract_document_v1_ingestions_extract_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExtractRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExtractResult"];
        };
      };
      /** @description Request correlation mismatch. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request ID replay detected. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request schema validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  index_document_v1_ingestions_index_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IndexRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IndexResult"];
        };
      };
      /** @description Request correlation mismatch. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request ID replay detected. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request schema validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  draft_log_v1_log_drafts_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogDraftRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogDraftResult"];
        };
      };
      /** @description Request correlation mismatch. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request ID replay detected. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request schema validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  draft_procedure_v1_procedure_drafts_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProcedureDraftRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProcedureDraftResult"];
        };
      };
      /** @description Request correlation mismatch. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request ID replay detected. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request schema validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  revalidate_procedure_v1_procedure_drafts_revalidate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RevalidationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevalidationResult"];
        };
      };
      /** @description Request correlation mismatch. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request ID replay detected. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request schema validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  answer_question_v1_questions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QuestionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuestionResult"];
        };
      };
      /** @description Request correlation mismatch. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request ID replay detected. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Request schema validation failed. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Service authentication unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
}
