"use client";

import { Bell, ChevronRight, CircleHelp, Moon, Monitor, Save, ShieldCheck, Sun } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button, Field } from "@/components/ui";
import { useTheme, type ThemeChoice } from "@/components/theme-provider";

const themes: { value: ThemeChoice; label: string; icon: typeof Sun }[] = [{ value: "light", label: "Light", icon: Sun }, { value: "dark", label: "Dark", icon: Moon }, { value: "system", label: "System", icon: Monitor }];

export default function SettingsPage() {
  const { theme, setTheme } = useTheme();
  return <AppShell title="Settings"><div className="settings-grid"><section className="settings-panel profile-panel"><h2>Profile</h2><div className="avatar-row"><div className="avatar">JS</div><Button variant="secondary">Change</Button></div><Field label="Display name" required><input defaultValue="John Smith" /></Field><Field label="Work email (SSO)"><input defaultValue="john.smith@company.com" disabled /></Field><Field label="Job title (optional)"><input defaultValue="Reliability Engineer" /></Field><Field label="Support contact email"><input defaultValue="john.smith@company.com" type="email" /></Field><Button icon={<Save size={17} />}>Save changes</Button></section><div className="settings-column"><section className="settings-panel"><h2>Appearance</h2><p className="section-label">Theme</p><div className="theme-grid">{themes.map(({ value, label, icon: Icon }) => <button className={`theme-option ${theme === value ? "theme-option-active" : ""}`} key={value} onClick={() => setTheme(value)} aria-pressed={theme === value}><Icon size={28} /><strong>{label}</strong></button>)}</div><p className="field-hint">Applies to all workspaces and dashboards.</p></section><section className="settings-panel"><h2>Accessibility</h2><Toggle label="Reduced motion" description="Reduce animations and motion effects" /><Toggle label="Compact density" description="Show more content in less space" checked /></section><section className="settings-panel"><h2>Account &amp; support</h2><SupportRow icon={<ShieldCheck />} title="SSO & security" description="Manage single sign-on and security settings" /><SupportRow icon={<Bell />} title="Notification preferences" description="Manage email and in-app notifications" /><SupportRow icon={<CircleHelp />} title="Help & support" description="Get help and contact support" /></section></div><section className="settings-panel preview-panel"><h2>Preview ({theme === "dark" ? "Dark" : theme === "light" ? "Light" : "System"} theme)</h2><div className="preview-shell"><strong>P.A.T.C.H.</strong><div className="preview-content"><h3>Dashboard</h3><div className="preview-stat">Equipments<br /><b>128</b></div><div className="preview-stat">Active Projects<br /><b>6</b></div></div></div></section></div></AppShell>;
}

function Toggle({ label, description, checked }: { label: string; description: string; checked?: boolean }) { return <label className="toggle-row"><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" defaultChecked={checked} /><span className="toggle" aria-hidden="true" /></label>; }
function SupportRow({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) { return <a className="support-row" href="#">{icon}<span><strong>{title}</strong><small>{description}</small></span><ChevronRight size={18} /></a>; }